# Generated by Django 5.1.7 on 2025-05-04 11:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000)),
                ('inicio', models.DateField(default=datetime.date.today)),
                ('fin', models.DateField(default=datetime.date.today)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Asignada', 'Asignada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='Abierta', max_length=20)),
                ('notas', models.CharField(max_length=150)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEmpresaDjango.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000)),
                ('inicio', models.DateField(default=datetime.date.today)),
                ('fin', models.DateField(default=datetime.date.today)),
                ('presupuesto', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('empleados', models.ManyToManyField(to='appEmpresaDjango.empleado')),
                ('tareas', models.ManyToManyField(to='appEmpresaDjango.tarea')),
            ],
        ),
    ]
